### ISSUE TITLE
[FEATURE] Add an option to provide a list of columns to select from source

### ISSUE THREAD

**Issue by george-zubrienko** [SneaksAndData/arcane-framework-scala#21]
### Description

For the yaml we should add the following field:
```
columns: ["colA", "colB", ...]
```
If not empty, source query should be `select colA, colB...` instead of `select * from ...`

**Comment by george-zubrienko** [comment]
Update on the desired specification:
```
fieldSelectionRule:
   type: exclude | include
   fields:
    - colA
    - colB
```
